{% set name = "sparse" %}
{% set version = "0.4.1" %}
{% set sha256 = "4c770db50eda4922f09801f37ba065075f844e2415bd4ebaea9fa3f9ba89ad57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.13
    - scipy >=0.19

test:
  imports:
    - sparse

about:
  home: https://github.com/pydata/sparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Sparse multi-dimensional arrays for the PyData ecosystem'

  description: |
    sparse implements sparse multidimensional arrays on top of Numpy
    and scipy.sparse. It tries to mimic Numpy's ndarray API.
  doc_url: https://sparse.pydata.org/en/{{ version }}/
  dev_url: https://github.com/pydata/sparse

extra:
  recipe-maintainers:
    - hameerabbasi
    - mrocklin
    - jakevdp
