{% set name = "sparse" %}
{% set version = "0.15.1" %}
{% set sha256 = "973adcb88a8db8e3d8047953331e26d3f64a5657f9b46a6b859c47663c3eef99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # skip as per upstream req, also missing numba >=0.49 for s390x
  skip: True  # [py<39 or s390x]

requirements:
  build:
    - python
    - pip
    - wheel
    - setuptools 68.2.2
    - setuptools-scm 8.0.4
  run:
    - python
    - numpy >=1.17
    - scipy >=0.19
    - numba >=0.49

test:
  imports:
    - sparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sparse.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sparse multi-dimensional arrays for the PyData ecosystem
  description: |
    sparse implements sparse multidimensional arrays on top of Numpy
    and scipy.sparse. It tries to mimic Numpy's ndarray API.
  doc_url: https://sparse.pydata.org
  dev_url: https://github.com/pydata/sparse

extra:
  recipe-maintainers:
    - hameerabbasi
    - mrocklin
    - jakevdp
