{% set name = "sparse" %}
{% set version = "0.17.0" %}
{% set sha256 = "6b1ad51a810c5be40b6f95e28513ec810fe1c785923bd83b2e4839a751df4bf7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # skip as per upstream req, also missing numba >=0.49 for s390x
  skip: true  # [py<310 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python
    - numpy >=1.17
    - scipy >=0.19
    - numba >=0.49
  run_constrained:
    - finch-tensor >=0.2.12
    - finch-mlir >=0.0.2

test:
  imports:
    - sparse
  commands:
    - pip check
    - pytest -v --pyargs sparse
  requires:
    - pip
    - dask
    - pytest >=3.5

about:
  home: https://sparse.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sparse multi-dimensional arrays for the PyData ecosystem
  description: |
    sparse implements sparse multidimensional arrays on top of Numpy
    and scipy.sparse. It tries to mimic Numpy's ndarray API.
  doc_url: https://sparse.pydata.org
  dev_url: https://github.com/pydata/sparse

extra:
  recipe-maintainers:
    - hameerabbasi
    - mrocklin
    - jakevdp
