{% set name = "sparse" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b1ad51a810c5be40b6f95e28513ec810fe1c785923bd83b2e4839a751df4bf7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python
    - numpy >=1.17
    - numba >=0.49
  run_constrained:
    - finch-tensor >=0.2.12
    - finch-mlir >=0.0.2

# E   ModuleNotFoundError: No module named 'mlir_finch'
{% set ignore_tests = " --ignore=mlir_backend/tests" %}

test:
  imports:
    - sparse
  requires:
    - pip
    - dask
    - scipy
    - pytest >=3.5
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ ignore_tests }} --pyargs sparse.tests

about:
  home: https://sparse.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sparse multi-dimensional arrays for the PyData ecosystem
  description: |
    sparse implements sparse multidimensional arrays on top of Numpy
    and scipy.sparse. It tries to mimic Numpy's ndarray API.
  doc_url: https://sparse.pydata.org
  dev_url: https://github.com/pydata/sparse

extra:
  recipe-maintainers:
    - hameerabbasi
    - mrocklin
    - jakevdp
