{% set name = "sparse" %}
{% set version = "0.11.0" %}
{% set sha256 = "c7a03de03ffa993dfcde681feb14d07a1287ab3db25f23b2a9199d81494636f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pydata/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.13
    - scipy >=0.19
    - numba >=0.49

test:
  imports:
    - sparse

about:
  home: https://github.com/pydata/sparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sparse multi-dimensional arrays for the PyData ecosystem

  description: |
    sparse implements sparse multidimensional arrays on top of Numpy
    and scipy.sparse. It tries to mimic Numpy's ndarray API.
  doc_url: https://sparse.pydata.org/en/{{ version }}/
  dev_url: https://github.com/pydata/sparse

extra:
  recipe-maintainers:
    - hameerabbasi
    - mrocklin
    - jakevdp
