travis:
  secure:
    BINSTAR_TOKEN: I4NNsBFlpwZCvyd/EdReR7gXwIR+zZXOpazMMpY20Vmx8srvu2MVTQZwyNM9q10jJHue+DCYHtyiIpQOKZg+BmueX6IKYFvG47lNm5yA1XOYouCDEAO54PHwjQFd8+FsR9hzXfQL420Cv1L23XfkpUhiav4INr2Ghv1oRgjE1h849svsp2Ye2k/ZB6oRxAAAnji6rft7UrkFCBytt/9EBLbQeJoqPPn0gZyYJRKKVniCfAuKiughFS7bP0wGvbRLkj9FbVvpfFindzWmw7ilJfSdZT1StFr5yf7gmXC6wPqxMjkEHg6Z5r5Lev6luqiz8t8jWsPX8J/VHyZDF+HRDbva3TAW7CzXKPzR3IuMdeQcXbC7dwMSt38Ys7dxX9Gn9mMUfwub0cJ0SbKmcCbUNsi7gtBE9rkuSf9JhpbgomGTS6FZ8UiJOPGsf5zEN9s/Cez3wJ+tHljeTWDG0Quqi739Qyr0Vl0uB80+SgIu9rN0DBGRzIz7jWGcfP5z5h2GLm4Do8U7A9hrfjTRdf2iM6RpMhIUY0vi/F633ddu3aI3ocGpyfrngZ8wjLLvgmS7KufX1PlGQDuPaT1sd36DqVQFjKW7BQnDLtZNGkXJP4eRPT6d1VgnGvwwhetlQYBgznd8OGtlPOmvNtSmXGEdrDOBuTiXgky4ZTo+hGifrBo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
