travis:
  secure:
    BINSTAR_TOKEN: hxDW2HTMezDMpJYCvHxvV0cQD2gnYmc+tCLqjIwBotsGRZGOWdkBxP0vlvMyD8tsNH5iC8eEEaMXQAkHf/0OvBPp4t8+PnPJclZ/VxTekV8J4l7k0brWgpGVMmammicX2vpQxbA0nEMxsuMKXw2W7cIYxl2LNPTtZ8COIkGqq+3PWTT1VkbgpTBaGnAxWYJPfIZgsQpUzZEiY5ikSh5aX3/E3IHzkTsS6NU/+w4FsfHvKheuylsmlGR6OBezMLpXtnmrbfAf4OWcyJhI+9GmAUaN8pKHDf9baMXELjs7RaJ/LYJRMl7k52OVe4stkk9PlDnAhLaw8tFxJV8qVqwH0Glj+LRGHsBWZ/dhd0do57EcsIFRsCYdwQWC7sjjndCw0XhQJRLQm0Y7SqdKCPdJy/r5X3dNjzs1EXjTJ8Dp3GtajvzzsPoflsqeqpmMs5dOH18/WauA94WWex1Ty3C4M/d1xShBZ5o8RgfztTUvf5y7WF+9mptJg95wBNmrfeLKfQfv4uD9qFhh1tmLwkMdrQiPvVyC6eQV8tjr3O4oHSqy7SAqZPmjo2aFXo6nzvZJaKlGTXJdYOPPk7dam57N6xNtVKFStlH7RAa6zg6JLHFGYYoh0UlJPMAMCDvv/svsXmJHsiznCM6ZHd0Km9J36hceJTlOQ1/kfrgpioIovrw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
